import { useTheme } from 'next-themes'
import Head from 'next/head'
import { useEffect } from 'react'
import Hero from './Components/Hero'
import Navbar from './Components/Navbar'

export default function Home() {
  const { theme, setTheme } = useTheme("dark")
  return (
    <div>
      <Head>
        <title>Vijeth K </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='h-screen bg-white dark:bg-black'>
        <div className='px-4 md:px-16 lg:px-24 max-w-6xl mx-auto font-inter'>
          <Navbar setTheme={setTheme} theme={theme} />
          <Hero />
        </div>
      </main>
    </div>
  )
}
